-- CandidateOutcome: research-grade dataset for evaluating filter/score/gate value
CREATE TABLE "CandidateOutcome" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "scanId" TEXT NOT NULL,
    "scanDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ticker" TEXT NOT NULL,
    "name" TEXT,
    "sleeve" TEXT NOT NULL,
    "sector" TEXT,
    "cluster" TEXT,
    "status" TEXT NOT NULL,
    "stageReached" TEXT NOT NULL,
    "passedTechFilter" BOOLEAN NOT NULL DEFAULT 0,
    "passedRiskGates" BOOLEAN NOT NULL DEFAULT 0,
    "passedAntiChase" BOOLEAN NOT NULL DEFAULT 0,
    "blockedByRegime" BOOLEAN NOT NULL DEFAULT 0,
    "blockedReasons" TEXT,
    "regime" TEXT NOT NULL,
    "price" REAL NOT NULL DEFAULT 0,
    "ma200" REAL NOT NULL DEFAULT 0,
    "adx" REAL NOT NULL DEFAULT 0,
    "plusDI" REAL NOT NULL DEFAULT 0,
    "minusDI" REAL NOT NULL DEFAULT 0,
    "atrPct" REAL NOT NULL DEFAULT 0,
    "atr" REAL NOT NULL DEFAULT 0,
    "efficiency" REAL NOT NULL DEFAULT 0,
    "volumeRatio" REAL NOT NULL DEFAULT 0,
    "relativeStrength" REAL NOT NULL DEFAULT 0,
    "hurstExponent" REAL,
    "hurstWarn" BOOLEAN NOT NULL DEFAULT 0,
    "atrSpiking" BOOLEAN NOT NULL DEFAULT 0,
    "atrSpikeAction" TEXT,
    "bqs" REAL,
    "fws" REAL,
    "ncs" REAL,
    "rankScore" REAL NOT NULL DEFAULT 0,
    "entryTrigger" REAL NOT NULL DEFAULT 0,
    "stopPrice" REAL NOT NULL DEFAULT 0,
    "distancePct" REAL NOT NULL DEFAULT 0,
    "entryMode" TEXT,
    "suggestedShares" REAL,
    "suggestedRiskGbp" REAL,
    "suggestedRiskPct" REAL,
    "suggestedCostGbp" REAL,
    "antiChaseReason" TEXT,
    "earningsAction" TEXT,
    "daysToEarnings" INTEGER,
    "riskGatesFailed" TEXT,
    "dataFreshness" TEXT,
    "tradePlaced" BOOLEAN NOT NULL DEFAULT 0,
    "tradeLogId" TEXT,
    "actualFill" REAL,
    "priceAtScan" REAL,
    "fwdReturn5d" REAL,
    "fwdReturn10d" REAL,
    "fwdReturn20d" REAL,
    "mfeR" REAL,
    "maeR" REAL,
    "reached1R" BOOLEAN,
    "reached2R" BOOLEAN,
    "reached3R" BOOLEAN,
    "stopHit" BOOLEAN,
    "enrichedAt" DATETIME
);

CREATE UNIQUE INDEX "CandidateOutcome_scanId_ticker_key" ON "CandidateOutcome"("scanId", "ticker");
CREATE INDEX "CandidateOutcome_scanId_idx" ON "CandidateOutcome"("scanId");
CREATE INDEX "CandidateOutcome_ticker_idx" ON "CandidateOutcome"("ticker");
CREATE INDEX "CandidateOutcome_scanDate_idx" ON "CandidateOutcome"("scanDate");
CREATE INDEX "CandidateOutcome_status_idx" ON "CandidateOutcome"("status");
CREATE INDEX "CandidateOutcome_regime_idx" ON "CandidateOutcome"("regime");
